---
title: "Lab 2"
author: "Thomas Weil GIS 3"
output:
  html_document:
    theme: cosmo
    toc: true
    df_print: paged
  pdf_document: default
---



# Libraries

```{r}
library(sf)
library(raster)
library(dplyr)
library(stringr) # for working with strings (pattern matching)
library(tidyr) 
library(spData)
library(ggplot2)
data(us_states)
data(us_states_df)
library(tmap)
```
# Data manipulation

Create a new variables
Filter out Distrcit of Columbia, a massive outlier
```{r}
usa<- us_states
usa<- mutate(usa, pop_density= (total_pop_10)/as.numeric(AREA))
class(usa)
usa<- filter(usa, NAME != "District of Columbia")
```
# Summary
```{r}

summary(usa)
```
#Non-spatial figure
Create a historgram
```{r}
ggplot<- ggplot(usa, aes(x=pop_density))+geom_histogram(color="blue", fill="white", bins=30)
ggplot
```

# Map
Create a map
```{r}

tm_shape(usa)+tm_fill("pop_density", style= "jenks", palette = "PuBu", title="Density")+ tm_borders()+tm_layout(main.title="Population density 2015",legend.position = c("right", "bottom"), legend.text.size = .66, main.title.position = "center")+tm_compass()


```

#Data Sourcs

* us_states data set by Bivand, Jakub Nowosad, Robin Lovelace, available at https://github.com/Nowosad/spData/blob/master/data/us_states.rda 
